### ISSUE TITLE
Create issues

### ISSUE THREAD

**Issue by quellus** [BeardBytesLife/GDSpinner#1]
I would like to contribute, but I don't know what work has been done, what work needs to be done, and what the road map looks like.

I would like to have issues representing what work needs to be done so that I can have some direction on how I can help as well as have a way to indicate what work I am doing and get feedback on progress.

**Comment by TrentSaggus** [comment]
Thanks for the feedback @quellus , I'm new to the open source development cycle so any feedback is greatly appreciated. I have started to add issues for things being worked on and to do, will continue to add as things progress.
Thanks again for the feedback :)
